// Generated by setup. Firebase options for HATOD (android config).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not configured for this project.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'FlutterFire is unable to configure for $defaultTargetPlatform. '
          'Add its FirebaseOptions below.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKQ2pR0WuRUVb3yZMXuAdLUW0OKlO0evg',
    appId: '1:47921660234:android:2ad897acacbae0041e41b3',
    messagingSenderId: '47921660234',
    projectId: 'hailing-3b955',
    storageBucket: 'hailing-3b955.appspot.com',
  );
}
